<a href="https://colab.research.google.com/github/Ahsrah-09/Machine-Learning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [2]:
iris=load_iris()
print("keys=",iris.keys())

keys= dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
df=pd.DataFrame(iris['data'])

In [4]:
print("Features:", iris.feature_names)


Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print("Class Labels:", iris.target_names)


Class Labels: ['setosa' 'versicolor' 'virginica']


In [6]:
X=df

In [7]:
y = iris['target']


In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
Knn=KNeighborsClassifier(n_neighbors=5)

In [10]:
Knn.fit(X_train,y_train)

KNeighborsClassifier()

In [11]:
y_pred=Knn.predict(X_test)

In [12]:
Cm=metrics.confusion_matrix(y_test,y_pred)

In [13]:
print(Cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [14]:
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))

Accuracy = 1.0


In [15]:
error_rate = 1 - metrics.accuracy_score(y_test, y_pred)


In [16]:
print("Errorrate=",error_rate)

Errorrate= 0.0


In [17]:
x_new=np.array([[5,2.4,3.7,1.6]])

In [18]:
prediction=Knn.predict(x_new)

In [19]:
print('New data sample is predicted as',iris['target_names'][prediction])

New data sample is predicted as ['versicolor']
