<a href="https://colab.research.google.com/github/Ahsrah-09/Machine-Learning/blob/main/naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [2]:
iris=load_iris()
print("keys=",iris.keys())

keys= dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
df=pd.DataFrame(iris['data'])

In [4]:
print("Features:", iris.feature_names)


Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print("Class Labels:", iris.target_names)


Class Labels: ['setosa' 'versicolor' 'virginica']


In [6]:
X=df

In [7]:
y = iris['target']


In [8]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
print("Training data = ",X_train,y_train)

Training data =         0    1    2    3
22   4.6  3.6  1.0  0.2
15   5.7  4.4  1.5  0.4
65   6.7  3.1  4.4  1.4
11   4.8  3.4  1.6  0.2
42   4.4  3.2  1.3  0.2
..   ...  ...  ...  ...
71   6.1  2.8  4.0  1.3
106  4.9  2.5  4.5  1.7
14   5.8  4.0  1.2  0.2
92   5.8  2.6  4.0  1.2
102  7.1  3.0  5.9  2.1

[120 rows x 4 columns] [0 0 1 0 0 2 1 0 0 0 2 1 1 0 0 1 2 2 1 2 1 2 1 0 2 1 0 0 0 1 2 0 0 0 1 0 1
 2 0 1 2 0 2 2 1 1 2 1 0 1 2 0 0 1 1 0 2 0 0 1 1 2 1 2 2 1 0 0 2 2 0 0 0 1
 2 0 2 2 0 1 1 2 1 2 0 2 1 2 1 1 1 0 1 1 0 1 2 2 0 1 2 2 0 2 0 1 2 2 1 2 1
 1 2 2 0 1 2 0 1 2]


In [11]:
model=GaussianNB()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [12]:
print("Accuracy =", metrics.accuracy_score(y_test, y_pred))


Accuracy = 1.0


In [13]:
print("Confusion matrix =\n", metrics.confusion_matrix(y_test, y_pred))


Confusion matrix =
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [14]:
x_new=np.array([[5,2.4,3.7,1.6]])

In [15]:
prediction=model.predict(x_new)

In [16]:
print('New data sample is predicted as',iris['target_names'][prediction])

New data sample is predicted as ['versicolor']
